### ISSUE TITLE
"else if" throws an error

### ISSUE THREAD

**Issue by ownlyme** [jac3km4/redscript-ide-vscode#4]
```
module test

@wrapMethod(DamageManager)
public final static func PostProcess(hitEvent: ref<gameHitEvent>) -> Void
{
	let test = true;
	if test
	{}
	else if test
	{}
}
```
throws an error on the else if line.
`[Info  - 1:50:23 PM] error at 9:7: expected one of "!=", "%", "&", "&&", "&=", "(", "*", "*=", "+", "+=", "-", "-=", ".", "/", "/=", ";", "<", "<=", "=", "==", ">", ">=", "?", "[", "^", "{", "|", "|=", "||"`
that also means if you have any else if somewhere in your code, the syntax helper doesn't work.

(the compiler interprets "else if" correctly)

**Comment by jac3km4** [comment]
should be fixed in the latest release

**Comment by ownlyme** [comment]
works, thank you very much!
