### ISSUE TITLE
StateContext without ref<> as function argument stops IDE from working

### ISSUE THREAD

**Issue by JonnesTT** [jac3km4/redscript-ide-vscode#8]
Declaring a function argument to be StateContext without placing it inside a ref<> or wref<> statement and hovering over a code piece causes the error: 
```
[Error - 2:48:02 AM] Request textDocument/hover failed.
  Message: compiler error: compilation error: cannot emit function call (probably invalid signature) is not supported
  Code: 1 
```
In this state, the IDE also doesn't mark anything. Except, for some cases where it marks the last whitespace in the file, or the first declaration after the faulty declaration as missing a field declaration.

For replication, the minimal unit of code I've found this error in was:
```
@wrapMethod(LocomotionAirEvents) 
protected func OnEnter( stateContext : StateContext, scriptInterface : ref<StateGameScriptInterface> ) -> Void
	{
	}
```
When replacing StateContext with ref<StateContext>, it worked again.

**Comment by jac3km4** [comment]
I think this should be fixed now @JonnesTT, can you re-test and close if fixed?
