### ISSUE TITLE
Formatting removes comments and newlines

### ISSUE THREAD

**Issue by Zhincore** [jac3km4/redscript-ide-vscode#9]
Hello,
I don't like that the formatting removes my comments and new lines, can this be made optional so I can disable it?
Comments are pretty crucial imo :D

Thanks

**Comment by jac3km4** [comment]
handling comments and newlines isn't properly implemented yet, it'll require some work in the parser, but yeah removing all comments and newlines isn't the desired behavior

**Comment by jac3km4** [comment]
@Zhincore the formatter should now preserve comments and newlines between statements
